### PR TITLE
Fix --prefix issue for service deps

### LINKED ISSUE #56: npm install --prefix fails on Windows
Hello,
the command to install services (npm install --prefix SERVICE_PATH) doesn't work on Windows.

It looks like it's an open issue https://github.com/npm/npm/issues/20245

### PR DESCRIPTION
**Pull request by atrovato**
Use folder iso --prefix
Works well with Windows

Fix #56

### CODE REVIEW

**Comment by atrovato** [comment]
Ignore this PR... it installs all deps into main folder... not expected behavior...
Search in progress...

**Comment by atrovato** [comment]
But it checks the services availability:

```
/home/travis/build/GladysAssistant/gladys-4-playground/server/services/mqtt/index.js
  10:24  error  Unable to resolve path to module 'mqtt'  import/no-unresolved
/home/travis/build/GladysAssistant/gladys-4-playground/server/services/telegram/index.js
  7:31  error  Unable to resolve path to module 'node-telegram-bot-api'  import/no-unresolved
/home/travis/build/GladysAssistant/gladys-4-playground/server/services/usb/index.js
  5:30  error  Unable to resolve path to module 'serialport'  import/no-unresolved
/home/travis/build/GladysAssistant/gladys-4-playground/server/services/zwave/index.js
  7:25  error  Unable to resolve path to module 'openzwave-shared'  import/no-unresolved
```

**Comment by atrovato** [comment]
It works, but changes the server package.json file to add each services as node file module...

@Pierre-Gilles let me know your opinion...

**Comment by Pierre-Gilles** [comment]
To be honest I'm not a big fan! 

1/ It's adding a dependencies in version 0.0.4 published 5 years ago... As you can see in the current package.json, there are only a few dependencies, carefully chosen for their popularity and stability. We don't want to be locked with that kind of dependencies...

Screenshot 2019-05-19 at 12 29 10

But isn't that just a mistake because you did `npm install folder`? 

2/ I want that the server could be installed without necessarily installing the services. 

I think the fix is waaaay simpler. ```cd services/${SERVICE_NAME} && npm install && cd ..` ?

**Comment by atrovato** [comment]
I tried to set the version to gladys-server root package.json, it generates another error "eloop: too many symbolic links encountered" because it creates a 'gladys-server' symlink into the service node_modules folder...

So for now I'm testing your solution...

**Pull request merged**
